version: '2'
services:
  nginx:
    build: services/nginx
    hostname: nginx
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  php:
    build: services/php
    volumes:
     - ./application:/var/www/html
    hostname: php
    container_name: php
    working_dir: /var/www/html
    networks:
     - appnet
  mysql:
    build: services/mysql
    hostname: mysql
    container_name: mysql
    volumes:
     - data:/var/lib/mysql
    environment:
     MYSQL_USERNAME: admin
     MYSQL_PASSWORD: secret
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
